### ISSUE TITLE
Math Magicians: refactor with hooks- code explanation

### ISSUE THREAD

**Issue by TamaraDimov** [TamaraDimov/math-magician#4]
- [ ] The code begins with importing React and useState from the React library, 
- [ ] Within the Calculator function, the useState hook is called to create a state variable named results that holds an object with three properties: 
 - total
 -  next
 -  operation

The total property holds the current total value of the calculator, next holds the value of the next number or decimal entered by the user, and operation holds the current mathematical operation that should be performed on total and next.

- [x] The handleClick function is defined next. This function is passed as a callback to all of the calculator buttons and is responsible for updating the state of the Calculator component based on the user's input. 

 It extracts the text content of the button that was clicked, and calls the calculate function with the current results state and the text content of the clicked button as arguments. The calculate function returns an updated results object based on the user's input, and the setRes function is called to update the results state with the new results object.

**Comment by amejid** [comment]
Hi @TamaraDimov, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Calculator functionality working as expected :heavy_check_mark: 
- App built with functional components :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TamaraDimov** [comment]
@amejid ,
Thank you for your fast response.
